
// TODO: Define all Sensor IDs

// CHECK: Define all Sensor IDs
enum SensorID {
    KEY_SWITCH,
    BATTERY_TEMP,
    COOLANT_TEMP,
    ACCELERATOR_POT_1,
    ACCELERATOR_POT_2,
    WHEEL_SPEED_FL,
    WHEEL_SPEED_FR,
    WHEEL_SPEED_RL,
    WHEEL_SPEED_RR,
    LED_ARRAY_1,
    LED_ARRAY_2,
    LED_ARRAY_3,
    SEVEN_SEG_1,
    SEVEN_SEG_2,
    ACCELEROMETER,
    GPS,
    DAMPER_POT_FL,
    DAMPER_POT_FR,
    DAMPER_POT_RL,
    DAMPER_POT_RR,
    STEERING_ENCODER,
    BRAKE_SWITCH,
    STRAIN_GAUGE_1,
    STRAIN_GAUGE_2,
    STRAIN_GAUGE_3,
    STRAIN_GAUGE_4,
    MOTOR_TEMP,
    WALKIE_TALKIE_BUTTON,
};
